version: '3.0'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=praktikum
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${POSTGRES_DEV_PORT}:5432
    volumes:
      - app-volume:/var/lib/postgresql/data

volumes:
  app-volume: